name: My First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "My first GitHub Actions Job"
            
            - name: List the files
              run: ls -la

            - name: Create text file
              run: echo "Hey, Hi. Running inside the pipeline" >> hello.txt        
            
            - name: Read the README file
              run: cat hello.txt