name: ASCII Generator
on:
    push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Install Cowsay
              run: |
                sudo apt-get update -y
                sudo apt-get install cowsay -y
            - name: List all cowsay animals
              run: cowsay -l >> animals.txt    

            - name: Execute
              run: cowsay -f stegosaurus "Gwwwwwwww" >> dragon.txt

            - name: Works
              run: |
                ls -la
                git status