name: ASCII Generator
on:
    push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Install Cowsay
              run: |
                sudo apt-get update -y
                sudo apt-get install cowsay -y
            - name: Execute
              run: cowsay -f cow "Ambaaaa" >> cow.txt

            - name: Display file
              run: cat cow.txt