name: ASCII Generator
on:
    push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            
            - name: Execute shell script
              run: bash script.sh

            - name: Add and commit files
              uses: stefanzweifel/git-auto-commit-action@v6
              with:
                commit_message: "Added files"