name: Multi Job Flow
on:
    push
jobs:
    Job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Install cowsay
              run: |
                sudo apt-get update
                sudo apt-get install cowsay -y
            - name: Execute cowsay
              run: cowsay "Hello, I'm a Linux cow" >> cow.txt
    Job-2:
        runs-on: ubuntu-latest
        needs: Job-1
        steps:
            - name: Print cows.txt
              run: cat cows.txt